name: Build and Deploy React App via FTP

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run React build script
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          ftp-server: ftp.binodtamang.com
          ftp-username: deploy@binodtamang1.com.np
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build
          git-ftp-args: "--all --force"
